/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package de.kramhal.coffeebutts

import de.kramhal.coffeebutts.model.Coffee
import de.kramhal.coffeebutts.model.Order
import org.springframework.web.bind.annotation.PostMapping
import org.springframework.web.bind.annotation.RequestBody
import org.springframework.web.bind.annotation.RestController

@RestController
class CoffeeServices {

    data class CoffeeOrder(val type: Coffee.Type)

    @PostMapping("/order")
    fun placeOrder(@RequestBody order: CoffeeOrder) {
        Order(Coffee(order.type))
    }
}